name: Check PR

on:
  pull_request:
    branches: [prod, staging]
    types: [opened, synchronize, reopened]

jobs:
  check:
    name: Check PR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Check eslint
        run: npm run lint:check

      - name: Typescript check
        run: npm run ts:check

      - name: Test
        run: npm run test -- --coverage

      - uses: actions/upload-artifact@4
        with:
          name: coverage-lcov
          path: coverage

      - name: Build
        run: |
          npm pkg delete scripts.prepare
          npm run build

  sonarcube:
    runs-on: ubuntu-latest
    needs: check
    concurrency:
      group: ${{ github.ref }}-sonarcube
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: coverage-lcov
          path: coverage

      - id: package-version
        run: npx @lomray/microservices-cli package-version

      - uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
        with:
          args: >
            -Dsonar.projectVersion=${{ steps.package-version.outputs.version }}
