name: Sonarqube

on:
  push:
    branches: [ prod ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcube:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-sonarcube
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: package-version
        run: npx @lomray/microservices-cli package-version

      - uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
        with:
          args: >
            -Dsonar.projectVersion=${{ steps.package-version.outputs.version }}
