name: SSR BOOST Release

on:
  workflow_call:
    inputs:
      build-folder:
        required: false
        type: string
        default: build
      has-release-asset:
        required: false
        type: boolean
        default: false
    secrets:
      github-token:
        required: true
    outputs:
      version:
        description: "New package version"
        value: ${{ jobs.release.outputs.version }}

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-release
      cancel-in-progress: true
    outputs:
      version: ${{ steps.package-version.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Create release asset
        if: ${{ inputs.has-release-asset }}
        run: zip -r build.zip ${{ inputs.build-folder }} package.json package-lock.json README.md

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}

      - name: Get version
        id: package-version
        run: npx @lomray/microservices-cli package-version
