name: SSR BOOST Docker build

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      image-name:
        required: true
        type: string
      version:
        required: true
        type: string
      app-build-path:
        required: true
        type: string
      should-skip-artifacts:
        required: false
        type: boolean
        default: false
      should-checkout:
        required: false
        type: boolean
        default: false
    secrets:
      github-token:
        required: true
      extra-build-args:
        required: false
    outputs:
      image-tag:
        description: "Docker image with new tag version"
        value: ${{ jobs.docker-build.outputs.image-tag }}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-build-docker
      cancel-in-progress: true
    outputs:
      # get docker image tag with version
      image-tag: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}

    steps:
      - uses: actions/checkout@v4
        if: ${{ inputs.should-checkout }}

      - uses: actions/download-artifact@v4
        if: ${{ !inputs.should-skip-artifacts }}
        with:
          name: build-artifact

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.github-token }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry }}/${{ inputs.image-name }}
          tags: |
            type=raw,prefix={{branch}}-,value=${{ inputs.version }}
            type=raw,prefix=latest-,value={{branch}}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_PATH=${{ inputs.app-build-path }}
            ${{ secrets.extra-build-args }}
