name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 30
          days-before-close: 7
          stale-issue-label: 'no-issue-activity'
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs.'
          close-issue-message: 'The issue has been closed for inactivity.'
